package home;

public class HomePageWebElements {

    public static final String enrollWebElementByCss="#enroll";
    public static final String cardOrAccountWebElementFieldByXpath="//input[@name='acctNumberField']";
    public static final String ssnWebElementFieldByXpath="//input[@name='ssNumberField']";
    public static final String continueButtonById="verifyCustomerAccount";
    public static final String validateByErrorMessageByXpath="//p[@class='spartaMessage-title']";
    public static final String checkingWebElementCSS="#navChecking > span.title";
    public static final String savingWebElementCSS="#navSavings > span.title";
    public static final String creditCardsWebElementsCSS="#navCreditCards > span.title";
    public static final String homeLoansWebElementsCSS="#navHomeLoans > span.title";
    public static final String autoLoansWebElementsCSS="#navAutoLoans > span.title";
    public static final String investingWebElementsCSS="#navInvesting > span.title";
    public static final String betterMoneyWebElementsCSS="#navBetterMoneyHabits > span.title";
    public static final String smallBusinessWebElementsID="NAV_BUSINESS_ADVANTAGE";
    public static final String wealthManagementWebElementsXPATH="/html/body/header/div[1]/div/ul[1]/li[3]/a";
    public static final String businessAndInstitutionsWebElementsCSS="#NAV_BUSINESS_INSTITUTIONS";
    public static final String securityWebElementsID="NAV_SECURITY";
    public static final String aboutUsWebElementsCSS="#NAV_ABOUT_US";
    public static final String enEspanolWebElementsCSS="#NAV_EN_ES";
    public static final String contactUsWebElementsCSS="#NAV_CONTACT_US";
    public static final String helpWebElementsCSS="#NAV_HELP";
    public static final String findClosestLocationWebElementsID="finCenterLocator";
    public static final String scheduleAppointmentWebElementsID="apptScheduler";
    public static final String dealsAllDayWebElementsCSS="#DZT1QUOU > div.info-box > div.heading";
    public static final String checkingWithRightFeaturesWebElementsCSS="#DCTAQT3I > div.info-box > div.heading";
    public static final String lifeServicesWebElementsID="yniLifeServicesCta";
    public static final String openCheckingAccountByClass="spa-btn spa-btn--primary spa-btn--medium masthead-cta-btn";
    public static final String advantageSafeBalanceByID="ProductDetails_P3_Opt1_CTA_Top";
    public static final String advantagePlusByID="ProductDetails_P3_Opt2_CTA_Top";
    public static final String advantageRelationshipByID="ProductDetails_P3_Opt3_CTA_Top";
    public static final String mortgageByID="mortgages";
    public static final String mortgageApplyByID="prequalify-now-medium";
    public static final String refinanceByID="refinance";
    public static final String validateMortgageRefinanceByCSS="#skip-to-h1";
    public static final String homeEquityByID="homeEquity";
    public static final String validateHomeEquityByXpath="//div[contains(text(),'Make the equity in your home work for you')]";
    public static final String cashRewardsCreditCardsByID="cashRewardsCards";
    public static final String travelRewardsCardsByID="travelRewardsCards";
    public static final String lowerInterestCardsByID="lowerInterestRateCards";
    public static final String pointsRewardsCardsByID="pointsRewardsCards";
    public static final String buildCreditCardsByID="buildCreditCards";
    public static final String cardsForStudentsByID="cardsForStudents";
    public static final String getMobileAppByID="getTheMobileApp";
    public static final String getTheAppByID="header_get_app";
    public static final String validateGetAppByXpath="//h4[contains(text(),'Get the Mobile Banking app')]";
    public static final String manageCreditCardAccountByID="manageCreditCardAccount";
    public static final String validateManageCreditCardByID="skip-to-h1";
    public static final String findCreditCardQuicklyByXpath="//div[contains(text(),'Find a credit card quickly')]";
    public static final String validateFindCreditCardByCSS="#skip-to-h1";
    public static final String applyNowUnderAutoLoansByID="autoApplyNow";
    public static final String applyNowUnderNewPageByID="refi-button";
    public static final String autoLoanRatesByID="autoLoanRates";
    public static final String autoLoanApplicationByID="calculateAutoLoanPayment";
    public static final String autoLoanTotalLoanAmountByID="totalLoanAmountField";
    public static final String autoLoanTermsInMonthsByID="term";
    public static final String autoLoanInterestRateFieldByID="interestRateField";
    public static final String autoLoanCalculatePaymentByID="calculateButton";
    public static final String validateLoanCalculatorByID="amount";
}
