package home;

public class HomePageWebElements<LocationsXpath, rentACarByXpath> {
    public static final String loginXpathWebElement = "//button[text()='Log in']";
    public static final String webelementSignUpXPATH = "/html/body/app-root/app-home/ngc-global-nav/header/div/nav/div/div[2]/ngc-login/div/div[1]/div/a";
    public static final String webelementLoginXpath = "/html/body/app-root/app-home/ngc-global-nav/header/div/nav/div/div[2]/ngc-login/div/div[2]/div/form/button";
    public static final String signUpTitle = "Join SkyMiles® Loyalty Program : Delta Air Lines";
    public static final String logingURL = "https://www.delta.com/login/loginPage?staticurl=";
    public static final String bookWebElementXpath = "//a[@id='headPrimary1']";
    public static final String bookTitle = "Airline Tickets & Flights: Book Direct with Delta Air Lines - Official Site";
    public static final String flightStatusTitle = "//*[@id=\"headPrimary4\"]";
    public static final String baggageTitle = "Baggage Policy and Fees | Delta Air Lines";
    public static final String skymilesXpath = "//a[@id=\"headSectab2\"]";
    public static final String flightDealsTitle = "Flight Deals: Find Cheap Airfare & Discounts on Airline Tickets : Delta";
    public static final String destinations = "//*[@id=\"headPrimary2\"]";
    public static final String flightProtection = "//*[@id=\"secondary-static-link-16\"]";
    public static final String feed = "//*[@id='feed']";
    public static final String needHelpElementID = "headSectab3";
    public static final String accessibleTravelServicesXpath = "//*[@id=\"secPanel3\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[6]";
    public static final String accessibleTravelServicesURL = "https://www.delta.com/us/en/accessible-travel-services/overview";
    public static final String petTravelElementID = "secondary-static-link-7";
    public static final String petTravelExpectedText = "Delta Pet Policy : Flying with Dogs, Cats & More : Delta Air Lines";
    public static final String vaccationDealsXpath = "//*[@id=\"homepage:banner-promoquilt\"]/div/div[2]/div/div/div/div[1]/div/div/ul/li[2]/a/span[1]";
    public static final String deltaAmexCardsXpath = "//*[@id=\"amex\"]";
    public static final String shopHotelsID = "\"home-shop-2\"";
    public static final String rentACarXpath = "//*[@id=\"homepage:banner-promoquilt\"]/div/div[2]/div/div/div/div[1]/div/div/ul/li[4]/a/span[1]";
    public static final String giftCardsXpath = "//*[@id=\"homepage:banner-promoquilt\"]/div/div[2]/div/div/div/div[1]/div/div/ul/li[5]/a";
    public static final String commonCheckedBaggageFeesXpath = "//*[@id=\"maincontent\"]/div[4]/div/div/div/div/div/div/div/div/div[1]/span";
    public static final String specialCircumstancesXpath = "//*[@id=\"secPanel3\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[9]";
    public static final String getSpecialCircumstancesURL = "https://www.delta.com/us/en/special-circumstances/overview";
    public static final String mobileXpath = "//*[@id=\"secPanel3\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[11]";
    public static final String mobileUrl = "https://www.delta.com/us/en/delta-digital/mobile";
    public static final String receiptsXpath = "//*[@id=\"secPanel3\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[4]";
    public static final String recieptsUrl = "https://www.delta.com/us/en/need-help/support-other-information#receipts";

    public static final String needHelpTabIDWebElement = "headSectab3";
    public static final String certificateAndECreditIDWebElement = "secondary-static-link-4";
    public static final String canadaEnglish = "//button[text()='Canada - English']";
    public static final String getSkymilesHelpXpath = "//*[@id=\"secPanel3\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[10]";
//    public static final String validateSkyMilesHelpByTitleExpected="SkyMiles Help : Delta Air Lines";
    public static final String accessibleTravelServicesByXpath="//*[@id=\"secPanel3\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[6]";
    public static final String childandInfandTravelByXpath="//*[@id=\"secPanel3\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[7]";
    public static final String flightStatusByClass="nav-link app-link nav-link-flightstatus";
    public static final String flightStatusByTitle="Join SkyMiles® Loyalty Program : Delta Air Lines";
    public static final String getReceiptsByXpath="//*[@id=\"secondary-static-link-3\"]";
    public static final String supportingYouThroughYourTravelJourney="//*[@id=\"homepage:banner-promoquilt\"]/div/div[3]/div/div/div/div/div[2]/h2/div";
    public static final String travelInfoByClass="nav-link static-link d-none d-lg-block static-link-secondarynav";
    public static final String travelInfoByID = "headSectab1";
    public static final String tripProtectionByID="secondary-static-link-16";
    public static final String coronavirusUpdatesByXpath="//*[@id=\"secPanel3\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[1]";
    public static final String flightStatusElementXpath="//a[text()='FLIGHT STATUS']";
    public static final String validateFlightStatusByXpath="//label[@class='floatinglabel']";
    public static final String myTripsElementByClass="nav-link app-link nav-link-mytrips";
    public static final String validateMyTripsByXpath="//label[@class='floatinglabel ng-star-inserted']";
    public static final String aircraftByID="secondary-static-link-11";
    public static final String flightScheduleByID="secondary-static-link-7";
    public static final String validateFlightSchduleByXpath="//div[@id='maincontent']/dl-flightsearch/div/div[2]/div/div/div/div[2]/h1";
    public static final String airportMapsNLocationsById="secondary-static-link-5";
    public static final String validateAirportMapsNLocationsByCSS="#maincontent > div.intro > div > div > div > div > div:nth-child(2) > span > h1";
    public static final String deltaVacationsByXpath="//*[@id=\"secPanel1\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[13]";
    public static final String validateDeltaVacationsByTitle="Delta Vacations";
    public static final String checkInByXPATH="//a[@class='nav-link app-link nav-link-check-in']";
    public static final String confirmationNumberByXPATH="//input[@class='form-control mb-2 mb-sm-0 input-mobile-tab-class ng-pristine ng-invalid ng-touched']";
    public static final String fromAirportByClass="airport-desc";
    public static final String selectAirportJFKByXPATH="//*[@id=\"airport-serach-panel\"]/div/div[2]/div/ul/li[1]";
    public static final String radioButtonById="btn-checkin-submit";
    public static final String validateConfirmationNumberByID="findbyfailed";
    public static final String onBoardExperienceByID="secondary-static-link-9";
    public static final String validateOnBoardExperienceByTitle="Fly With Delta | Compare Flight Classes & Services | Delta Air Lines";
    public static final String baggageByXpath="//*[@id=\"secPanel1\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[3]";
    public static final String validateBaggageByTitle="Baggage Policy and Fees | Delta Air Lines";
    public static final String airlinePartnersByXpath="//*[@id=\"secPanel1\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[2]";
    public static final String validateAirlinePartnersByTitle="Overview";
    public static final String shopHotelsByXpath="//*[@id=\"secPanel1\"]/ngc-app-sec-links-content/div/div/div[2]/div[3]/ul/li[15]";
    public static final String validateShopHotelsByTitle="Delta - Deals & Discounts for Hotel Reservations from Luxury Hotels to Budget Accommodations";

}